#!/bin/sh

echo 'Fetching updates from master'
git fetch master && git rebase origin/master
echo '                                                              [DONE]'

echo 'Fetching updates from upstream'
git remote add upstream git@github.com:thoughtbot/dotfiles.git
git fetch upstream && git rebase upstream/master
echo '                                                              [DONE]'

echo 'Installing pre-requisites: zsh and rcm'
brew bundle dotfiles/Brewfile
echo '                                                              [DONE]'

echo 'Changing shell for current user to zsh'
chsh -s $(which zsh)
echo '                                                              [DONE]'

echo 'Setting up symlinks'
ln -s $HOME/Dropbox/dotfiles $HOME/dotfiles
ln -s $HOME/Dropbox/dotfiles-local $HOME/dotfiles-local
echo '                                                              [DONE]'

echo 'Installing dotfiles'
rcup -d dotfiles -x README.md -x LICENSE -x Brewfile
echo '                                                              [DONE]'
