#!/bin/sh

if [ -h ~/dotfiles ]; then
  cd ~/Dropbox/dotfiles

  echo 'Fetching updates from robkilby/master'
  git fetch origin && git rebase origin/master
  echo '                                                              [DONE]'

  cd ~/

  if [ ! -h ~/dotfiles-local ]; then
    echo 'Setting up symlinks'
    if [ -e ~/Dropbox/dotfiles-local ]; then
      ln -s ~/Dropbox/dotfiles-local ~/dotfiles-local
    else
      echo 'Dotfiles local customisations not found in Dropbox. Skipping.'
    fi
    echo '                                                              [DONE]'
  fi

  echo 'Updating dotfiles'
  rcup
  echo '                                                              [DONE]'
else
  echo 'Dotfiles not setup. Run setup script first.'
fi
