#!/bin/sh

if [ ! -e $HOME/.vim/bundle/Vundle.vim ]; then
  git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
fi
vim -u $HOME/.vimrc.bundles +PluginInstall +qa

[ -f $HOME/connections.xml ] && echo 'Skipping connections.xml; file exists' || ln -s $HOME/dotfiles-local/.connections.xml $HOME/connections.xml
